//

// engine.cpp : Put all your graphics stuff in this file. This is kind of the graphics module.
// In here, you should type all your OpenGL commands, and you can also type code to handle
// input platform events (e.g to move the camera or react to certain shortcuts), writing some
// graphics related GUI options, and so on.
//

#include "engine.h"
#include <imgui.h>
#include <stb_image.h>
#include <stb_image_write.h>
#include <assimp/cimport.h>
#include <assimp/scene.h>
#include <assimp/postprocess.h>
#include <vector>

#define BINDING(b) b
#define MAKE_GLVERSION(major, minor) (major*10 + minor)
#define MAKE_GLSLVERSION(major, minor) (major*100 + minor*10)

static App* gApp = NULL;


// https://www.khronos.org/opengl/wiki/Debug_Output
void OnGlError(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar* message, const void* userParam)
{
    if (severity == GL_DEBUG_SEVERITY_NOTIFICATION)
        return;

    ELOG("OpenGL debug message: %s", message);

    switch (source)
    {
    case GL_DEBUG_SOURCE_API:             ELOG(" - source: GL_DEBUG_SOURCE_API"); break; // Calls to the OpenGL API
    case GL_DEBUG_SOURCE_WINDOW_SYSTEM:   ELOG(" - source: GL_DEBUG_SOURCE_WINDOW_SYSTEM"); break; // Calls to a window-system API
    case GL_DEBUG_SOURCE_SHADER_COMPILER: ELOG(" - source: GL_DEBUG_SOURCE_SHADER_COMPILER"); break; // A compiler for a shading language
    case GL_DEBUG_SOURCE_THIRD_PARTY:     ELOG(" - source: GL_DEBUG_SOURCE_THIRD_PARTY"); break; // An application associated with OpenGL
    case GL_DEBUG_SOURCE_APPLICATION:     ELOG(" - source: GL_DEBUG_SOURCE_APPLICATION"); break; // Generated by the user of this application
    case GL_DEBUG_SOURCE_OTHER:           ELOG(" - source: GL_DEBUG_SOURCE_OTHER"); break; // Some source that isn't one of these
    }

    switch (type)
    {
    case GL_DEBUG_TYPE_ERROR:               ELOG(" - type: GL_DEBUG_TYPE_ERROR"); break; // An error, typically from the API
    case GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR: ELOG(" - type: GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR"); break; // Some behavior marked deprecated has been used
    case GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR:  ELOG(" - type: GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR"); break; // Something has invoked undefined behavior
    case GL_DEBUG_TYPE_PORTABILITY:         ELOG(" - type: GL_DEBUG_TYPE_PORTABILITY"); break; // Some functionality the user relies upon is not portable
    case GL_DEBUG_TYPE_PERFORMANCE:         ELOG(" - type: GL_DEBUG_TYPE_PERFORMANCE"); break; // Code has triggered possible performance issues
    case GL_DEBUG_TYPE_MARKER:              ELOG(" - type: GL_DEBUG_TYPE_MARKER"); break; // Command stream annotation
    case GL_DEBUG_TYPE_PUSH_GROUP:          ELOG(" - type: GL_DEBUG_TYPE_PUSH_GROUP"); break; // Group pushing
    case GL_DEBUG_TYPE_POP_GROUP:           ELOG(" - type: GL_DEBUG_TYPE_POP_GROUP"); break; // foo
    case GL_DEBUG_TYPE_OTHER:               ELOG(" - type: GL_DEBUG_TYPE_OTHER"); break; // Some type that isn't one of these
    }

    switch (severity)
    {
    case GL_DEBUG_SEVERITY_HIGH:         ELOG(" - severity: GL_DEBUG_SEVERITY_HIGH"); break; // All OpenGL Errors, shader compilation/linking errors, or highly-dangerous undefined behavior
    case GL_DEBUG_SEVERITY_MEDIUM:       ELOG(" - severity: GL_DEBUG_SEVERITY_MEDIUM"); break; // Major performance warnings, shader compilation/linking warnings, or the use of deprecated functionality
    case GL_DEBUG_SEVERITY_LOW:          ELOG(" - severity: GL_DEBUG_SEVERITY_LOW"); break; // Redundant state change performance warning, or unimportant undefined behavior
    case GL_DEBUG_SEVERITY_NOTIFICATION: ELOG(" - severity: GL_DEBUG_SEVERITY_NOTIFICATION"); break; // Anything that isn't an error or performance issue.
    }
}

struct DebugEvent
{
    DebugEvent(App* app, u32 renderGroupIdx)
    {
        if (glPushDebugGroup) glPushDebugGroup(GL_DEBUG_SOURCE_APPLICATION, 1, -1, app->renderGroups[renderGroupIdx].name);
    }
    ~DebugEvent()
    {
        if (glPopDebugGroup) glPopDebugGroup();
    }
};

u32 GetTimerQueryIndex(u32 frameMod, u32 renderGroupIdx, u32 beginOrEnd)
{
    ASSERT(frameMod < MAX_GPU_FRAME_DELAY, "Frame mod out of bounds");
    ASSERT(renderGroupIdx < MAX_RENDER_GROUPS, "Render group out of bounds");
    ASSERT(beginOrEnd < 2, "An event can only have begin and end markers");
    u32 queryIdx = frameMod * MAX_RENDER_GROUPS * 2 + renderGroupIdx * 2 + beginOrEnd;
    return queryIdx;
}

void ProfileEvent_Init(App* app)
{
    glGenQueries(ARRAY_COUNT(app->timerQueries), app->timerQueries);
}

void ProfileEvent_BeginFrame(App* app)
{
    const u32 renderGroupIdx = app->frameRenderGroup;
    const GLuint timerQuery = app->timerQueries[ GetTimerQueryIndex(app->frameMod, renderGroupIdx, 0) ];
    glQueryCounter(timerQuery, GL_TIMESTAMP);
}

void ProfileEvent_EndFrame(App* app)
{
    const u32 renderGroupIdx = app->frameRenderGroup;
    const GLuint timerQuery = app->timerQueries[ GetTimerQueryIndex(app->frameMod, renderGroupIdx, 1) ];
    glQueryCounter(timerQuery, GL_TIMESTAMP);
}

struct ProfileEvent
{
    const GLuint beginTimerQuery;
    const GLuint endTimerQuery;

    ProfileEvent(App* app, u32 renderGroupIdx)
        : beginTimerQuery( app->timerQueries[ GetTimerQueryIndex(app->frameMod, renderGroupIdx, 0) ] )
        , endTimerQuery  ( app->timerQueries[ GetTimerQueryIndex(app->frameMod, renderGroupIdx, 1) ] )
    {
        glQueryCounter(beginTimerQuery, GL_TIMESTAMP);
    }
    ~ProfileEvent()
    {
        glQueryCounter(endTimerQuery, GL_TIMESTAMP);
    }
};

u32 RegisterRenderGroup(App* app, const char* pName)
{
    ASSERT(app->renderGroupCount < MAX_RENDER_GROUPS, "MAX_RENDER_GROUPS limit reached");
    u32 groupIdx = app->renderGroupCount++;
    app->renderGroups[groupIdx].name = pName;
    return groupIdx;
}

#define RENDER_GROUP(name) \
    static const u32   renderGroupIdx##__FILE__##__LINE__ = RegisterRenderGroup(gApp, name); \
    const DebugEvent   debugEvent    ##__FILE__##__LINE__(gApp, renderGroupIdx##__FILE__##__LINE__); \
    const ProfileEvent profileEvent  ##__FILE__##__LINE__(gApp, renderGroupIdx##__FILE__##__LINE__);

bool IsPowerOf2(u32 value)
{
    return value && !(value & (value - 1));
}

u32 Align(u32 value, u32 alignment)
{
    return (value + alignment - 1) & ~(alignment - 1);
}

Buffer CreateBufferRaw(u32 size, GLenum type, GLenum usage)
{
    Buffer buffer = {};
    buffer.size = size;
    buffer.type = type;

    glGenBuffers(1, &buffer.handle);
    glBindBuffer(type, buffer.handle);
    glBufferData(type, buffer.size, NULL, usage);
    glBindBuffer(type, 0);

    return buffer;
}

#define CreateConstantBufferRaw(size)      CreateBufferRaw(size, GL_UNIFORM_BUFFER,       GL_STREAM_DRAW)
#define CreateStaticVertexBufferRaw(size)  CreateBufferRaw(size, GL_ARRAY_BUFFER,         GL_STATIC_DRAW)
#define CreateStaticIndexBufferRaw(size)   CreateBufferRaw(size, GL_ELEMENT_ARRAY_BUFFER, GL_STATIC_DRAW)
#define CreateDynamicVertexBufferRaw(size) CreateBufferRaw(size, GL_ARRAY_BUFFER,         GL_STREAM_DRAW)

void BindBuffer(const Buffer& buffer)
{
    if (buffer.handle)
        glBindBuffer(buffer.type, buffer.handle);
}

void MapBuffer(Buffer& buffer, GLenum access)
{
    glBindBuffer(buffer.type, buffer.handle);
    buffer.data = (u8*)glMapBuffer(buffer.type, access);
    buffer.head = 0;
}

void UnmapBuffer(Buffer& buffer)
{
    glUnmapBuffer(buffer.type);
    glBindBuffer(buffer.type, 0);
}

void AlignHead(Buffer& buffer, u32 alignment)
{
    ASSERT(IsPowerOf2(alignment), "The alignment must be a power of 2");
    buffer.head = Align(buffer.head, alignment);
}

void PushAlignedData(Buffer& buffer, const void* data, u32 size, u32 alignment)
{
    ASSERT(buffer.data != NULL, "The buffer must be mapped first");
    AlignHead(buffer, alignment);
    ASSERT(buffer.head + size <= buffer.size, "Trying to push data out of bounds");
    MemCopy((u8*)buffer.data + buffer.head, data, size);
    buffer.head += size;
}

#define PushData(buffer, data, size) PushAlignedData(buffer, data, size, 1)
#define PushUInt(buffer, value) { u32 v = value; PushAlignedData(buffer, &v, sizeof(v), 4); }
#define PushVec3(buffer, value) PushAlignedData(buffer, value_ptr(value), sizeof(value), sizeof(vec4))
#define PushVec4(buffer, value) PushAlignedData(buffer, value_ptr(value), sizeof(value), sizeof(vec4))
#define PushMat3(buffer, value) PushAlignedData(buffer, value_ptr(value), sizeof(value), sizeof(vec4))
#define PushMat4(buffer, value) PushAlignedData(buffer, value_ptr(value), sizeof(value), sizeof(vec4))

Buffer& GetCurrentConstantBuffer( App* app )
{
    ASSERT( app->currentConstantBufferIdx <= app->device.constantBuffers.size(), "Current buffer out of bounds" );
    while ( app->currentConstantBufferIdx >= app->device.constantBuffers.size() ) {
        app->device.constantBuffers.push_back( CreateConstantBufferRaw(app->device.uniformBufferMaxSize) );
    }
    return app->device.constantBuffers[ app->currentConstantBufferIdx ];
}

void BeginConstantBufferRecording( App *app )
{
    app->currentConstantBufferIdx = 0;
    Buffer& buffer = GetCurrentConstantBuffer(app);
    MapBuffer( buffer, GL_WRITE_ONLY );
}

Buffer& GetMappedConstantBufferForRange( App *app, u32 sizeInBytes )
{
    Buffer& buffer = GetCurrentConstantBuffer(app);

    AlignHead(buffer, app->device.uniformBufferAlignment);

    if ( buffer.head + sizeInBytes <= buffer.size )
    {
        return buffer;
    }
    else
    {
        UnmapBuffer(buffer);
        ASSERT( app->currentConstantBufferIdx < app->device.constantBuffers.size(), "Constant buffer memory is full" );
        app->currentConstantBufferIdx++;
        Buffer& nextBuffer = GetCurrentConstantBuffer(app);
        MapBuffer( nextBuffer, GL_WRITE_ONLY );
        return nextBuffer;
    }
}

void EndConstantBufferRecording( App *app )
{
    Buffer& buffer = app->device.constantBuffers[app->currentConstantBufferIdx];
    UnmapBuffer(buffer);
}

GLuint CreateProgramFromSource(String programSource, int glslVersion, const char* shaderName)
{
    GLchar  infoLogBuffer[1024] = {};
    GLsizei infoLogBufferSize = sizeof(infoLogBuffer);
    GLsizei infoLogSize;
    GLint   success;

    String glslVersionHeader    = FormatString("#version %u\n", glslVersion);
    String glslVersionDefine    = FormatString("#define VERSION %u\n", glslVersion);
    String shaderNameDefine     = FormatString("#define %s\n", shaderName);
    String vertexShaderDefine   = MakeString("#define VERTEX\n");
    String fragmentShaderDefine = MakeString("#define FRAGMENT\n");

    const GLchar* vertexShaderSource[] = {
        glslVersionHeader.str,
        glslVersionDefine.str,
        shaderNameDefine.str,
        vertexShaderDefine.str,
        programSource.str
    };
    const GLint vertexShaderLengths[] = {
        (GLint) glslVersionHeader.len,
        (GLint) glslVersionDefine.len,
        (GLint) shaderNameDefine.len,
        (GLint) vertexShaderDefine.len,
        (GLint) programSource.len
    };
    const GLchar* fragmentShaderSource[] = {
        glslVersionHeader.str,
        glslVersionDefine.str,
        shaderNameDefine.str,
        fragmentShaderDefine.str,
        programSource.str
    };
    const GLint fragmentShaderLengths[] = {
        (GLint) glslVersionHeader.len,
        (GLint) glslVersionDefine.len,
        (GLint) shaderNameDefine.len,
        (GLint) fragmentShaderDefine.len,
        (GLint) programSource.len
    };

    GLuint vshader = glCreateShader(GL_VERTEX_SHADER);
    glShaderSource(vshader, ARRAY_COUNT(vertexShaderSource), vertexShaderSource, vertexShaderLengths);
    glCompileShader(vshader);
    glGetShaderiv(vshader, GL_COMPILE_STATUS, &success);
    if (!success)
    {
        glGetShaderInfoLog(vshader, infoLogBufferSize, &infoLogSize, infoLogBuffer);
        ELOG("glCompileShader() failed with vertex shader %s\nReported message:\n%s\n", shaderName, infoLogBuffer);
    }

    GLuint fshader = glCreateShader(GL_FRAGMENT_SHADER);
    glShaderSource(fshader, ARRAY_COUNT(fragmentShaderSource), fragmentShaderSource, fragmentShaderLengths);
    glCompileShader(fshader);
    glGetShaderiv(fshader, GL_COMPILE_STATUS, &success);
    if (!success)
    {
        glGetShaderInfoLog(fshader, infoLogBufferSize, &infoLogSize, infoLogBuffer);
        ELOG("glCompileShader() failed with fragment shader %s\nReported message:\n%s\n", shaderName, infoLogBuffer);
    }

    GLuint programHandle = glCreateProgram();
    glAttachShader(programHandle, vshader);
    glAttachShader(programHandle, fshader);
    glLinkProgram(programHandle);
    glGetProgramiv(programHandle, GL_LINK_STATUS, &success);
    if (!success)
    {
        glGetProgramInfoLog(programHandle, infoLogBufferSize, &infoLogSize, infoLogBuffer);
        ELOG("glLinkProgram() failed with program %s\nReported message:\n%s\n", shaderName, infoLogBuffer);
    }

    glUseProgram(0);

    glDetachShader(programHandle, vshader);
    glDetachShader(programHandle, fshader);
    glDeleteShader(vshader);
    glDeleteShader(fshader);

#if 0
    // Shader reflection
    ILOG("SHADER REFLECTION FOR %s", shaderName);
    GLint   blockCount;
    GLchar  blockName[128];
    GLsizei blockNameLen;
    GLint   blockSize;
    GLint   blockUniformCount;
    GLint   blockUniformIndices[128];
    GLint   blockUniformOffsets[128];
    GLint   blockUniformCounts[128];
    GLchar  uniformName[128];
    GLsizei uniformNameLen;
    GLint   uniformCount;
    GLenum  uniformType;
    glGetProgramiv(programHandle, GL_ACTIVE_UNIFORM_BLOCKS, &blockCount);
    for (u32 blockIdx = 0; blockIdx < blockCount; ++blockIdx)
    {
        glGetActiveUniformBlockName(programHandle, blockIdx, ARRAY_COUNT(blockName), &blockNameLen, blockName);
        glGetActiveUniformBlockiv(programHandle, blockIdx, GL_UNIFORM_BLOCK_DATA_SIZE, &blockSize);
        ILOG("- Uniform Block: %s (%d Bytes)", blockName, blockSize);

        glGetActiveUniformBlockiv(programHandle, blockIdx, GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS, &blockUniformCount );
        ASSERT(blockUniformCount <= ARRAY_COUNT(blockUniformIndices), "Uniform block exeeds the maximum number of fields");
        glGetActiveUniformBlockiv(programHandle, blockIdx, GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES, blockUniformIndices );

        glGetActiveUniformsiv(programHandle, blockUniformCount, (const GLuint*)blockUniformIndices, GL_UNIFORM_OFFSET, blockUniformOffsets);
        glGetActiveUniformsiv(programHandle, blockUniformCount, (const GLuint*)blockUniformIndices, GL_UNIFORM_SIZE, blockUniformCounts);

        for (u32 blockUniformIdx = 0; blockUniformIdx < blockUniformCount; blockUniformIdx++)
        {
            u32 uniformIdx = blockUniformIndices[blockUniformIdx];

            glGetActiveUniform(programHandle, uniformIdx, ARRAY_COUNT(uniformName), &uniformNameLen, &uniformCount, &uniformType, uniformName);
            ILOG("  -> uniform: %s (offset:%d count:%d)", uniformName, blockUniformOffsets[blockUniformIdx], blockUniformCounts[blockUniformIdx]);
        }
    }
#endif

    return programHandle;
}

VertexShaderLayout ExtractVertexShaderLayoutFromProgram(GLuint programHandle)
{
    VertexShaderLayout layout = {};

    GLint attributeCount = 0;
    char attributeName[128];
    GLsizei attributeNameLength;
    GLint attributeSize;
    GLenum attributeType;
    GLint attributeLocation;
    u8 attributeComponentCount = 0;

    glGetProgramiv(programHandle, GL_ACTIVE_ATTRIBUTES, &attributeCount);

    for (i32 i = 0; i < attributeCount; ++i)
    {
        glGetActiveAttrib(programHandle, i,
                          ARRAY_COUNT(attributeName),
                          &attributeNameLength,
                          &attributeSize,
                          &attributeType,
                          attributeName);

        attributeLocation = glGetAttribLocation(programHandle, attributeName);

        const GLint VertexStream_FirstInstancingStream = 6;
        if (attributeLocation >= VertexStream_FirstInstancingStream)
            continue;

        switch (attributeType)
        {
            case GL_FLOAT:      attributeComponentCount = 1; break;
            case GL_FLOAT_VEC2: attributeComponentCount = 2; break;
            case GL_FLOAT_VEC3: attributeComponentCount = 3; break;
            case GL_FLOAT_VEC4: attributeComponentCount = 4; break;
            default: INVALID_CODE_PATH("Unsupported attribute type");
        }

        layout.attributes.push_back({
            (u8)attributeLocation,
            (u8)attributeComponentCount
            });
    }

    return layout;
}


u32 LoadProgram(Device& device, const char* filepath, const char* programName)
{
    String programSource = ReadTextFile(filepath);

    Program program = {};
    program.handle = CreateProgramFromSource(programSource, device.glslVersion, programName);
    program.vertexInputLayout = ExtractVertexShaderLayoutFromProgram(program.handle);
    program.filepath = filepath;
    program.programName = programName;
    program.lastWriteTimestamp = GetFileLastWriteTimestamp(filepath);
    device.programs.push_back(program);

    return device.programs.size() - 1;
}

Image LoadImage(const char* filename)
{
    Image img = {};
    stbi_set_flip_vertically_on_load(true);
    img.pixels = stbi_load(filename, &img.size.x, &img.size.y, &img.nchannels, 0);
    if (img.pixels)
    {
        img.stride = img.size.x * img.nchannels;
    }
    else
    {
        ELOG("Could not open file %s", filename);
    }
    return img;
}

void FreeImage(Image image)
{
    stbi_image_free(image.pixels);
}

GLuint CreateTexture2DFromImage(Image image)
{
    GLenum internalFormat = GL_RGB8;
    GLenum dataFormat     = GL_RGB;
    GLenum dataType       = GL_UNSIGNED_BYTE;

    switch (image.nchannels)
    {
        case 3: dataFormat = GL_RGB; internalFormat = GL_RGB8; break;
        case 4: dataFormat = GL_RGBA; internalFormat = GL_RGBA8; break;
        default: ELOG("LoadTexture2D() - Unsupported number of channels");
    }

    GLuint texHandle;
    glGenTextures(1, &texHandle);
    glBindTexture(GL_TEXTURE_2D, texHandle);
    glTexImage2D(GL_TEXTURE_2D, 0, internalFormat, image.size.x, image.size.y, 0, dataFormat, dataType, image.pixels);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR_MIPMAP_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glGenerateMipmap(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, 0);

    return texHandle;
}

u32 LoadTexture2D(Device& device, const char* filepath)
{
    for (u32 texIdx = 0; texIdx < device.textures.size(); ++texIdx)
        if (device.textures[texIdx].filepath == filepath)
            return texIdx;

    Image image = LoadImage(filepath);

    if (image.pixels)
    {
        Texture tex = {};
        tex.handle = CreateTexture2DFromImage(image);
        tex.filepath = filepath;

        u32 texIdx = device.textures.size();
        device.textures.push_back(tex);

        FreeImage(image);
        return texIdx;
    }
    else
    {
        return UINT32_MAX;
    }
}

void ProcessAssimpMesh(const aiScene* scene, aiMesh *mesh, Mesh *myMesh, u32 baseMeshMaterialIndex, std::vector<u32>& submeshMaterialIndices, std::vector<float>& vertices, std::vector<u32>& indices)
{
    bool hasTexCoords = false;
    bool hasTangentSpace = false;

    const u32 vertexOffset = vertices.size() * sizeof(float);
    const u32 indexOffset = indices.size() * sizeof(u32);

    // process vertices
    for(unsigned int i = 0; i < mesh->mNumVertices; i++)
    {
        vertices.push_back(mesh->mVertices[i].x);
        vertices.push_back(mesh->mVertices[i].y);
        vertices.push_back(mesh->mVertices[i].z);
        vertices.push_back(mesh->mNormals[i].x);
        vertices.push_back(mesh->mNormals[i].y);
        vertices.push_back(mesh->mNormals[i].z);

        if(mesh->mTextureCoords[0]) // does the mesh contain texture coordinates?
        {
            hasTexCoords = true;
            vertices.push_back(mesh->mTextureCoords[0][i].x);
            vertices.push_back(mesh->mTextureCoords[0][i].y);
        }

        if(mesh->mTangents != nullptr && mesh->mBitangents)
        {
            hasTangentSpace = true;
            vertices.push_back(mesh->mTangents[i].x);
            vertices.push_back(mesh->mTangents[i].y);
            vertices.push_back(mesh->mTangents[i].z);

            // For some reason ASSIMP gives me the bitangents flipped.
            // Maybe it's my fault, but when I generate my own geometry
            // in other files (see the generation of standard assets)
            // and all the bitangents have the orientation I expect,
            // everything works ok.
            // I think that (even if the documentation says the opposite)
            // it returns a left-handed tangent space matrix.
            // SOLUTION: I invert the components of the bitangent here.
            vertices.push_back(-mesh->mBitangents[i].x);
            vertices.push_back(-mesh->mBitangents[i].y);
            vertices.push_back(-mesh->mBitangents[i].z);
        }
    }

    // process indices
    for(unsigned int i = 0; i < mesh->mNumFaces; i++)
    {
        aiFace face = mesh->mFaces[i];
        ASSERT(face.mNumIndices == 3, "Faces should have three vertices");
        for(unsigned int j = 0; j < face.mNumIndices; j++)
        {
            indices.push_back(face.mIndices[j]);
        }
    }

    // store the proper (previously proceessed) material for this mesh
    submeshMaterialIndices.push_back(baseMeshMaterialIndex + mesh->mMaterialIndex);

    // create the vertex format
    VertexBufferLayout vertexBufferLayout = {};
    vertexBufferLayout.attributes.push_back( VertexBufferAttribute{ 0, 3, 0 } );
    vertexBufferLayout.attributes.push_back( VertexBufferAttribute{ 1, 3, 3*sizeof(float) } );
    vertexBufferLayout.stride = 6 * sizeof(float);
    if (hasTexCoords)
    {
        vertexBufferLayout.attributes.push_back( VertexBufferAttribute{ 2, 2, vertexBufferLayout.stride } );
        vertexBufferLayout.stride += 2 * sizeof(float);
    }
    if (hasTangentSpace)
    {
        vertexBufferLayout.attributes.push_back( VertexBufferAttribute{ 3, 3, vertexBufferLayout.stride } );
        vertexBufferLayout.stride += 3 * sizeof(float);

        vertexBufferLayout.attributes.push_back( VertexBufferAttribute{ 4, 3, vertexBufferLayout.stride } );
        vertexBufferLayout.stride += 3 * sizeof(float);
    }

   // add the submesh into the mesh
   Submesh submesh = {};
   submesh.vertexBufferLayout = vertexBufferLayout;
   submesh.vertexOffset = vertexOffset;
   submesh.indexOffset = indexOffset;
   submesh.vertexCount = mesh->mNumVertices;
   submesh.indexCount = mesh->mNumFaces*3;
   myMesh->submeshes.push_back( submesh );
}

void ProcessAssimpMaterial(Device& device, aiMaterial *material, Material& myMaterial, String directory)
{
    aiString name;
    aiColor3D diffuseColor;
    aiColor3D emissiveColor;
    aiColor3D specularColor;
    ai_real shininess;
    material->Get(AI_MATKEY_NAME, name);
    material->Get(AI_MATKEY_COLOR_DIFFUSE, diffuseColor);
    material->Get(AI_MATKEY_COLOR_EMISSIVE, emissiveColor);
    material->Get(AI_MATKEY_COLOR_SPECULAR, specularColor);
    material->Get(AI_MATKEY_SHININESS, shininess);

    myMaterial.name = name.C_Str();
    myMaterial.albedo = vec3(diffuseColor.r, diffuseColor.g, diffuseColor.b);
    myMaterial.emissive = vec3(emissiveColor.r, emissiveColor.g, emissiveColor.b);
    myMaterial.smoothness = shininess / 256.0f;

    aiString aiFilename;
    if (material->GetTextureCount(aiTextureType_DIFFUSE) > 0)
    {
        material->GetTexture(aiTextureType_DIFFUSE, 0, &aiFilename);
        String filename = MakeString(aiFilename.C_Str());
        String filepath = MakePath(directory, filename);
        myMaterial.albedoTextureIdx = LoadTexture2D(device, filepath.str);
    }
    if (material->GetTextureCount(aiTextureType_EMISSIVE) > 0)
    {
        material->GetTexture(aiTextureType_EMISSIVE, 0, &aiFilename);
        String filename = MakeString(aiFilename.C_Str());
        String filepath = MakePath(directory, filename);
        myMaterial.emissiveTextureIdx = LoadTexture2D(device, filepath.str);
    }
    if (material->GetTextureCount(aiTextureType_SPECULAR) > 0)
    {
        material->GetTexture(aiTextureType_SPECULAR, 0, &aiFilename);
        String filename = MakeString(aiFilename.C_Str());
        String filepath = MakePath(directory, filename);
        myMaterial.specularTextureIdx = LoadTexture2D(device, filepath.str);
    }
    if (material->GetTextureCount(aiTextureType_NORMALS) > 0)
    {
        material->GetTexture(aiTextureType_NORMALS, 0, &aiFilename);
        String filename = MakeString(aiFilename.C_Str());
        String filepath = MakePath(directory, filename);
        myMaterial.normalsTextureIdx = LoadTexture2D(device, filepath.str);
    }
    if (material->GetTextureCount(aiTextureType_HEIGHT) > 0)
    {
        material->GetTexture(aiTextureType_HEIGHT, 0, &aiFilename);
        String filename = MakeString(aiFilename.C_Str());
        String filepath = MakePath(directory, filename);
        myMaterial.bumpTextureIdx = LoadTexture2D(device, filepath.str);
    }

    //myMaterial.createNormalFromBump();
}

void ProcessAssimpNode(const aiScene* scene, aiNode *node, Mesh *myMesh, u32 baseMeshMaterialIndex, std::vector<u32>& submeshMaterialIndices, std::vector<float>& vertices, std::vector<u32>& indices)
{
    // process all the node's meshes (if any)
    for(unsigned int i = 0; i < node->mNumMeshes; i++)
    {
        aiMesh *mesh = scene->mMeshes[node->mMeshes[i]];
        ProcessAssimpMesh(scene, mesh, myMesh, baseMeshMaterialIndex, submeshMaterialIndices, vertices, indices);
    }

    // then do the same for each of its children
    for(unsigned int i = 0; i < node->mNumChildren; i++)
    {
        ProcessAssimpNode(scene, node->mChildren[i], myMesh, baseMeshMaterialIndex, submeshMaterialIndices, vertices, indices);
    }
}

u32 LoadModel(Device& device, const char* filename)
{
    const aiScene* scene = aiImportFile(filename,
                                        aiProcess_Triangulate           |
                                        aiProcess_GenSmoothNormals      |
                                        aiProcess_CalcTangentSpace      |
                                        aiProcess_JoinIdenticalVertices |
                                        aiProcess_PreTransformVertices  |
                                        aiProcess_ImproveCacheLocality  |
                                        aiProcess_OptimizeMeshes        |
                                        aiProcess_SortByPType);

    if (!scene)
    {
        ELOG("Error loading mesh %s: %s", filename, aiGetErrorString());
        return UINT32_MAX;
    }

    device.meshes.push_back(Mesh{});
    Mesh& mesh = device.meshes.back();
    u32 meshIdx = (u32)device.meshes.size() - 1u;

    device.models.push_back(Model{});
    Model& model = device.models.back();
    model.meshIdx = meshIdx;
    u32 modelIdx = (u32)device.models.size() - 1u;

    String directory = GetDirectoryPart(MakeString(filename));

    // Create a list of materials
    const u32 baseMeshMaterialIndex = (u32)device.materials.size();
    for (unsigned int i = 0; i < scene->mNumMaterials; ++i)
    {
        device.materials.push_back(Material{});
        Material& material = device.materials.back();
        ProcessAssimpMaterial(device, scene->mMaterials[i], material, directory);
    }

    std::vector<float> vertices;
    std::vector<u32> indices;
    ProcessAssimpNode(scene, scene->mRootNode, &mesh, baseMeshMaterialIndex, model.materialIdx, vertices, indices);

    aiReleaseImport(scene);

    const u32 vertexBufferSize = vertices.size() * sizeof(float);
    const u32 indexBufferSize = indices.size() * sizeof(u32);

    mesh.vertexBuffer = CreateStaticVertexBufferRaw(vertexBufferSize);
    mesh.indexBuffer = CreateStaticIndexBufferRaw(indexBufferSize);

    MapBuffer(mesh.vertexBuffer, GL_WRITE_ONLY);
    MapBuffer(mesh.indexBuffer, GL_WRITE_ONLY);

    PushData(mesh.vertexBuffer, vertices.data(), vertexBufferSize);
    PushData(mesh.indexBuffer, indices.data(), indexBufferSize);

    UnmapBuffer(mesh.vertexBuffer);
    UnmapBuffer(mesh.indexBuffer);

    return modelIdx;
}

Vao CreateVAORaw(const Buffer&             indexBuffer,
                 const Buffer&             vertexBuffer,
                 u32                       vertexBufferOffset,
                 // TODO:
                 // const Buffer& instanceBuffer
                 // u32           instanceBufferOffset
                 const VertexBufferLayout& bufferLayout,
                 const VertexShaderLayout& shaderLayout,
                 const Program&            shaderProgram)
{
    // Create a new vao for this submesh/program
    GLuint vaoHandle = 0;
    glGenVertexArrays(1, &vaoHandle);
    glBindVertexArray(vaoHandle);

    BindBuffer(vertexBuffer);
    BindBuffer(indexBuffer);

    // We have to link all vertex inputs attributes to attributes in the vertex buffer
    for (u32 i = 0; i < shaderLayout.attributes.size(); ++i)
    {
        bool attributeWasLinked = false;

        // TODO: If it is a per-vertex attribute

        for (u32 j = 0; j < bufferLayout.attributes.size(); ++j)
        {
            if (shaderLayout.attributes[i].location == bufferLayout.attributes[j].location)
            {
                const u32 index  = bufferLayout.attributes[j].location;
                const u32 ncomp  = bufferLayout.attributes[j].componentCount;
                const u32 offset = bufferLayout.attributes[j].offset + vertexBufferOffset; // attribute offset + vertex offset
                const u32 stride = bufferLayout.stride;
                glVertexAttribPointer(index, ncomp, GL_FLOAT, GL_FALSE, stride, (void*)(u64)offset);
                glEnableVertexAttribArray(index);

                attributeWasLinked = true;
                break;
            }
        }

        ASSERT(attributeWasLinked, "The submesh should provide an attribute for each vertex input");

        // TODO: Else, check the instance buffer
    }

    glBindVertexArray(0);

    // Store it in the list of vaos for this submesh
    Vao vao = { vaoHandle, shaderProgram.handle };
    return vao;
}

Vao CreateVAORaw(const Buffer& vertexBuffer,
                 u32           vertexBufferOffset,
                 const VertexBufferLayout& bufferLayout,
                 const VertexShaderLayout& shaderLayout,
                 const Program& shaderProgram)
{
    Buffer invalidIndexBuffer = {};
    return CreateVAORaw(invalidIndexBuffer, vertexBuffer, vertexBufferOffset, bufferLayout, shaderLayout, shaderProgram);
}

GLuint FindVAO(Mesh& mesh, u32 submeshIndex, const Program& program)
{
    Submesh& submesh = mesh.submeshes[submeshIndex];

    // Try finding a vao for this submesh/program
    for (u32 i = 0; i < (u32)submesh.vaos.size(); ++i)
        if (submesh.vaos[i].programHandle == program.handle)
            return submesh.vaos[i].handle;

    Vao vao = CreateVAORaw(mesh.indexBuffer, mesh.vertexBuffer, submesh.vertexOffset, submesh.vertexBufferLayout, program.vertexInputLayout, program);
    submesh.vaos.push_back(vao);

    return vao.handle;
}

RenderTarget CreateRenderTargetRaw(String name, ivec2 displaySize, RenderTargetType type)
{
    GLenum internalFormat = GL_RGBA8;
    GLenum externalFormat = GL_RGBA;
    GLenum channelDataType = GL_UNSIGNED_BYTE;

    if (type == RenderTargetType_Depth)
    {
        internalFormat = GL_DEPTH_COMPONENT24;
        externalFormat = GL_DEPTH_COMPONENT;
        channelDataType = GL_FLOAT;
    }

    // Framebuffer
    GLuint textureHandle;
    glGenTextures(1, &textureHandle);
    glBindTexture(GL_TEXTURE_2D, textureHandle);
    glTexImage2D(GL_TEXTURE_2D, 0, internalFormat, displaySize.x, displaySize.y, 0, externalFormat, channelDataType, NULL);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glBindTexture(GL_TEXTURE_2D, 0);

    RenderTarget renderTarget = {};
    renderTarget.name         = name;
    renderTarget.size         = displaySize;
    renderTarget.handle       = textureHandle;
    renderTarget.type         = type;
    return renderTarget;
}

u32 CreateRenderTarget(Device& device, String name, RenderTargetType type, ivec2 size)
{
    RenderTarget renderTarget = CreateRenderTargetRaw(name, size, type);
    device.renderTargets.push_back(renderTarget);
    return device.renderTargets.size() -1 ;
}

void DestroyRenderTargetRaw(const RenderTarget& renderTarget)
{
    glDeleteTextures(1, &renderTarget.handle);
}

RenderPass CreateRenderPassRaw(Device& device, u32 attachmentCount, Attachment* attachments)
{
    GLuint framebufferHandle;
    glGenFramebuffers(1, &framebufferHandle);
    glBindFramebuffer(GL_FRAMEBUFFER, framebufferHandle);

    u32    colorBufferCount = 0;
    GLuint colorBuffers[16] = {};

    for (u32 i = 0; i < attachmentCount; ++i)
    {
        GLenum attachmentPoint = attachments[i].attachmentPoint;
        u32    renderTargetIdx = attachments[i].renderTargetIdx;
        RenderTarget& renderTarget = device.renderTargets[ renderTargetIdx ];
        glFramebufferTexture(GL_FRAMEBUFFER, attachmentPoint, renderTarget.handle, 0);

        if (attachmentPoint < GL_COLOR_ATTACHMENT8) {
            colorBuffers[colorBufferCount++] = renderTarget.handle;
        }
    }

    GLenum framebufferStatus = glCheckFramebufferStatus(GL_FRAMEBUFFER);
    if (framebufferStatus != GL_FRAMEBUFFER_COMPLETE)
    {
        switch (framebufferStatus)
        {
            case GL_FRAMEBUFFER_UNDEFINED:                     ELOG("GL_FRAMEBUFFER_UNDEFINED"); break;
            case GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT:         ELOG("GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT"); break;
            case GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: ELOG("GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT"); break;
            case GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER:        ELOG("GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER"); break;
            case GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER:        ELOG("GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER"); break;
            case GL_FRAMEBUFFER_UNSUPPORTED:                   ELOG("GL_FRAMEBUFFER_UNSUPPORTED"); break;
            case GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE:        ELOG("GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE"); break;
            case GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS:      ELOG("GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS"); break;
            default: ELOG("Unknown framebuffer status error");
        }
    }

    glDrawBuffers(colorBufferCount, colorBuffers);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);

    RenderPass renderPass = { framebufferHandle };
    renderPass.attachmentCount = attachmentCount;
    MemCopy(&renderPass.attachments, attachments, attachmentCount*sizeof(Attachment));
    return renderPass;
}

u32 CreateRenderPass(Device& device, u32 attachmentCount, Attachment* attachments)
{
    RenderPass renderPass = CreateRenderPassRaw(device, attachmentCount, attachments);
    device.renderPasses.push_back(renderPass);
    return device.renderPasses.size() - 1U;
}

void DestroyRenderPassRaw(const RenderPass& renderPass)
{
    glDeleteFramebuffers(1, &renderPass.framebufferHandle);
}

void BeginRenderPass( const Device& device, u32 renderPassIdx )
{
    const RenderPass& renderPass = device.renderPasses[renderPassIdx];
    glBindFramebuffer(GL_FRAMEBUFFER, renderPass.framebufferHandle);

    glClearColor(0.1f, 0.1f, 0.1f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
}

void EndRenderPass( const Device& )
{
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
}

void AddModelEntity(Scene& scene, u32 modelIndex, const mat4& worldMatrix)
{
    Entity entity = {};
    entity.type = EntityType_Model;
    entity.modelIndex = modelIndex;
    entity.worldMatrix = worldMatrix;
    scene.entities.push_back(entity);
}

void AddMeshEntity(Scene& scene, u32 meshIndex, u32 submeshIndex, const mat4& worldMatrix)
{
    Entity entity = {};
    entity.type = EntityType_Mesh;
    entity.meshIndex = meshIndex;
    entity.submeshIndex = submeshIndex;
    entity.worldMatrix = worldMatrix;
    scene.entities.push_back(entity);
}

void AddDirectionalLight(Scene& scene, const vec3& color, const vec3& direction)
{
    Light light = {};
    light.type = LightType_Directional;
    light.color = color;
    light.direction = direction;
    scene.lights.push_back(light);
}

void AddPointLight(Scene& scene, const vec3& color, const vec3& position)
{
    Light light = {};
    light.type = LightType_Point;
    light.color = color;
    light.position = position;
    scene.lights.push_back(light);
}

mat4 TransformScale(const vec3& scaleFactors)
{
    mat4 transform = scale(scaleFactors);
    return transform;
}

mat4 TransformPositionScale(const vec3& pos, const vec3& scaleFactors)
{
    mat4 transform = translate(pos);
    transform = scale(transform, scaleFactors);
    return transform;
}

void DebugDraw_Clear(DebugDraw& debugDraw)
{
    debugDraw.opaqueLineCount = 0;
    debugDraw.texQuadCount = 0;
}

void DebugDraw_MapBuffers(DebugDraw& debugDraw)
{
    MapBuffer(debugDraw.opaqueLineVertexBuffer, GL_WRITE_ONLY);
}

void DebugDraw_UnmapBuffers(DebugDraw& debugDraw)
{
    UnmapBuffer(debugDraw.opaqueLineVertexBuffer);
}

void DebugDrawLine(DebugDraw& debugDraw, const vec3& p1, const vec3& p2, const vec3& color)
{
    struct DebugLineVertex { vec3 pos; vec3 col; };
    DebugLineVertex vertex1 = { p1, color };
    DebugLineVertex vertex2 = { p2, color };
    PushAlignedData(debugDraw.opaqueLineVertexBuffer, &vertex1, sizeof(DebugLineVertex), 1);
    PushAlignedData(debugDraw.opaqueLineVertexBuffer, &vertex2, sizeof(DebugLineVertex), 1);
    debugDraw.opaqueLineCount++;
}

void DebugDrawTexturedQuad(DebugDraw& debugDraw, GLuint textureHandle, const vec4& rect)
{
    const u32 texQuadIdx = debugDraw.texQuadCount++;
    debugDraw.texQuadTextureHandles[texQuadIdx] = textureHandle;
    debugDraw.texQuadRects[texQuadIdx] = rect;
}

void InitDevice(Device& device)
{
    // First object is considered null
    device.textures.push_back(Texture{});
    device.materials.push_back(Material{});
    device.meshes.push_back(Mesh{});
    device.models.push_back(Model{});
    device.programs.push_back(Program{});
    device.constantBuffers.push_back(Buffer{});
    device.renderTargets.push_back(RenderTarget{});
    device.renderPasses.push_back(RenderPass{});

    sprintf(device.name, "%s\n", glGetString(GL_RENDERER));
    sprintf(device.glVersionString,"%s\n", glGetString(GL_VERSION));
    u32 majorVersion = device.glVersionString[0] - '0';
    u32 minorVersion = device.glVersionString[2] - '0';
    device.glVersion   = MAKE_GLVERSION(majorVersion, minorVersion);
    device.glslVersion = MAKE_GLSLVERSION(majorVersion, minorVersion);

    glGetIntegerv(GL_MAX_UNIFORM_BLOCK_SIZE, &device.uniformBufferMaxSize);
    glGetIntegerv(GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT, &device.uniformBufferAlignment);

    if (device.glVersion >= MAKE_GLVERSION(4, 3))
    {
        glDebugMessageCallback(OnGlError, &device);
    }
}

void InitEmbedded(Device& device, Embedded& embed)
{
    // Embedded geometry
    device.meshes.push_back(Mesh{});
    Mesh& mesh = device.meshes.back();
    embed.meshIdx = (u32)device.meshes.size() - 1u;

    mesh.vertexBuffer = CreateStaticVertexBufferRaw(MB(1));
    mesh.indexBuffer = CreateStaticIndexBufferRaw(MB(1));
    
    MapBuffer(mesh.vertexBuffer, GL_WRITE_ONLY);
    MapBuffer(mesh.indexBuffer, GL_WRITE_ONLY);

    // Screen-filling triangle
    {
        struct VertexV3V2
        {
            vec3 pos;
            vec2 uv;
        };

        const VertexV3V2 vertices[] = {
            { vec3(-1.0, -1.0, 0.0), vec2(0.0, 0.0) }, // bottom-left vertex
            { vec3( 3.0, -1.0, 0.0), vec2(2.0, 0.0) }, // bottom-right vertex
            { vec3(-1.0,  3.0, 0.0), vec2(0.0, 2.0) }, // top-left vertex
        };

        const u32 indices[] = { 0, 1, 2 };

        embed.blitSubmeshIdx = mesh.submeshes.size();
        mesh.submeshes.push_back(Submesh{});
        Submesh& submesh = mesh.submeshes.back();
        submesh.vertexOffset = mesh.vertexBuffer.head;
        submesh.indexOffset = mesh.indexBuffer.head;
        submesh.vertexCount = ARRAY_COUNT(vertices);
        submesh.indexCount = ARRAY_COUNT(indices);
        submesh.vertexBufferLayout.stride = sizeof(VertexV3V2);
        submesh.vertexBufferLayout.attributes.push_back(VertexBufferAttribute{0, 3, 0});
        submesh.vertexBufferLayout.attributes.push_back(VertexBufferAttribute{2, 2, sizeof(vec3)});

        PushData(mesh.vertexBuffer, vertices, sizeof(vertices));
        PushData(mesh.indexBuffer, indices, sizeof(indices));
    }

    // Floor plane
    {
        struct VertexV3V3V2
        {
            vec3 pos;
            vec3 nor;
            vec2 uv;
        };

        const VertexV3V3V2 vertices[] = {
            { vec3(-1.0, 0.0,  1.0), vec3(0.0, 1.0, 0.0), vec2(0.0, 0.0) }, // bottom-left vertex
            { vec3( 1.0, 0.0,  1.0), vec3(0.0, 1.0, 0.0), vec2(1.0, 0.0) }, // bottom-right vertex
            { vec3( 1.0, 0.0, -1.0), vec3(0.0, 1.0, 0.0), vec2(1.0, 1.0) }, // top-right vertex
            { vec3(-1.0, 0.0, -1.0), vec3(0.0, 1.0, 0.0), vec2(0.0, 1.0) }, // top-left vertex
        };

        const u32 indices[] = {
            0, 1, 2,
            0, 2, 3
        };

        embed.floorSubmeshIdx = mesh.submeshes.size();
        mesh.submeshes.push_back(Submesh{});
        Submesh& submesh = mesh.submeshes.back();
        submesh.vertexOffset = mesh.vertexBuffer.head;
        submesh.indexOffset = mesh.indexBuffer.head;
        submesh.vertexCount = ARRAY_COUNT(vertices);
        submesh.indexCount = ARRAY_COUNT(indices);
        submesh.vertexBufferLayout.stride = sizeof(VertexV3V3V2);
        submesh.vertexBufferLayout.attributes.push_back(VertexBufferAttribute{0, 3, 0});
        submesh.vertexBufferLayout.attributes.push_back(VertexBufferAttribute{1, 3, sizeof(vec3)});
        submesh.vertexBufferLayout.attributes.push_back(VertexBufferAttribute{2, 2, 2*sizeof(vec3)});

        PushData(mesh.vertexBuffer, vertices, sizeof(vertices));
        PushData(mesh.indexBuffer, indices, sizeof(indices));
    }

    // Sphere
    {
        struct VertexV3V3V2
        {
            vec3 pos;
            vec3 nor;
            vec2 uv;
        };

        const u32 HMAX = 16;
        const u32 VMAX = 8;

        std::vector<VertexV3V3V2> vertices;
        for (u32 h = 0; h < HMAX; ++h)
        {
            for (u32 v = 0; v < VMAX + 1; ++v)
            {
                const float yaw = 2.0f * PI * (float)h/(float)HMAX;
                const float pitch = PI * (float)v/(float)VMAX;
                const vec3 pos( sinf(pitch) * sinf(yaw),
                                cosf(pitch),
                                sinf(pitch) * cosf(yaw) );
                vertices.push_back( {pos, normalize(pos), vec2(0.0f, 0.0f)} );
            }
        }

        std::vector<u32> indices;
        for (u32 h = 0; h < HMAX; ++h)
        {
            for (u32 v = 0; v < VMAX; ++v)
            {
                const u32 a = h * (VMAX+1) + v;
                const u32 b = h * (VMAX+1) + v + 1;
                const u32 c = ((h+1)%HMAX) * (VMAX+1) + v + 1;
                const u32 d = ((h+1)%HMAX) * (VMAX+1) + v;
                indices.push_back(a);
                indices.push_back(b);
                indices.push_back(c);
                indices.push_back(a);
                indices.push_back(c);
                indices.push_back(d);
            }
        }

        embed.sphereSubmeshIdx = mesh.submeshes.size();
        mesh.submeshes.push_back(Submesh{});
        Submesh& submesh = mesh.submeshes.back();
        submesh.vertexOffset = mesh.vertexBuffer.head;
        submesh.indexOffset = mesh.indexBuffer.head;
        submesh.indexCount = indices.size();
        submesh.vertexCount = vertices.size();
        submesh.vertexBufferLayout.stride = sizeof(VertexV3V3V2);
        submesh.vertexBufferLayout.attributes.push_back(VertexBufferAttribute{0, 3, 0});
        submesh.vertexBufferLayout.attributes.push_back(VertexBufferAttribute{1, 3, sizeof(vec3)});
        submesh.vertexBufferLayout.attributes.push_back(VertexBufferAttribute{2, 2, 2*sizeof(vec3)});

        PushData(mesh.vertexBuffer, vertices.data(), vertices.size() * sizeof(VertexV3V3V2));
        PushData(mesh.indexBuffer, indices.data(), indices.size() * sizeof(u32));
    }

    UnmapBuffer(mesh.vertexBuffer);
    UnmapBuffer(mesh.indexBuffer);

    // Textures
    embed.diceTexIdx = LoadTexture2D(device, "dice.png");
    embed.whiteTexIdx = LoadTexture2D(device, "color_white.png");
    embed.blackTexIdx = LoadTexture2D(device, "color_black.png");
    embed.normalTexIdx = LoadTexture2D(device, "color_normal.png");
    embed.magentaTexIdx = LoadTexture2D(device, "color_magenta.png");

    // Materials
    Material defaultMaterial = {};
    defaultMaterial.name = "defaultMaterial";
    defaultMaterial.albedo = vec3(1.0);
    defaultMaterial.emissive = vec3(0.0);
    defaultMaterial.smoothness = 0.0;
    defaultMaterial.albedoTextureIdx = embed.whiteTexIdx;
    defaultMaterial.emissiveTextureIdx = embed.blackTexIdx;
    defaultMaterial.specularTextureIdx = embed.blackTexIdx;
    defaultMaterial.normalsTextureIdx = embed.normalTexIdx;
    defaultMaterial.bumpTextureIdx = embed.blackTexIdx;
    embed.defaultMaterialIdx = device.materials.size();
    device.materials.push_back(defaultMaterial);

    // Textured geometry program
    embed.texturedGeometryProgramIdx = LoadProgram(device, "shaders.glsl", "TEXTURED_GEOMETRY");
    Program& texturedGeometryProgram = device.programs[embed.texturedGeometryProgramIdx];
    embed.texturedGeometryProgram_TextureLoc = glGetUniformLocation(texturedGeometryProgram.handle, "uTexture");
}

void InitDebugDraw(Device& device, DebugDraw& debugDraw)
{
    debugDraw.opaqueProgramIdx = LoadProgram(device, "shaders.glsl", "DEBUG_DRAW_OPAQUE");
    debugDraw.opaqueLineVertexBuffer = CreateDynamicVertexBufferRaw(KB(256));
    debugDraw.opaqueLineCount = 0;
    u32 debugDrawOpaqueLineOffset = 0;
    VertexBufferLayout debugDrawOpaqueLineVertexBufferLayout = {};
    debugDrawOpaqueLineVertexBufferLayout.attributes.push_back(VertexBufferAttribute{ 0, 3, 0 });
    debugDrawOpaqueLineVertexBufferLayout.attributes.push_back(VertexBufferAttribute{ 5, 3, sizeof(vec3) });
    debugDrawOpaqueLineVertexBufferLayout.stride = 2 * sizeof(vec3);
    Program debugDrawOpaqueLineProgram = device.programs[debugDraw.opaqueProgramIdx];
    debugDraw.opaqueLineVao = CreateVAORaw(debugDraw.opaqueLineVertexBuffer,
                                           debugDrawOpaqueLineOffset,
                                           debugDrawOpaqueLineVertexBufferLayout,
                                           debugDrawOpaqueLineProgram.vertexInputLayout,
                                           debugDrawOpaqueLineProgram);
}

void InitForwardRender(Device& device, ForwardRenderData& forwardRenderData)
{
    forwardRenderData.programIdx = LoadProgram(device, "shaders.glsl", "FORWARD_RENDER");
    Program& forwardRenderProgram = device.programs[forwardRenderData.programIdx];
    forwardRenderData.uniLoc_Albedo = glGetUniformLocation(forwardRenderProgram.handle, "uAlbedo");

    forwardRenderData.instancingBuffer = CreateDynamicVertexBufferRaw(MB(16));
}

void InitScene(Device& device, Scene& scene, Embedded& embedded)
{
    // Models
    scene.patrickModelIndex = LoadModel(device, "Patrick/Patrick.obj");

    // Camera
    Camera& camera = scene.mainCamera;
    camera.yaw = -0.7f;
    camera.pitch = -0.3f;
    camera.position = vec3(7.0, 4.0, 7.0);

    // Model/mesh entities
    AddMeshEntity(scene, embedded.meshIdx, embedded.floorSubmeshIdx, TransformScale(vec3(100.0f)));
    AddMeshEntity(scene, embedded.meshIdx, embedded.sphereSubmeshIdx, TransformScale(vec3(2.0f)));
    const u32 ENTITY_MULTIPLIER = 10;
    const f32 ENTITY_SEPARATION = 3.0f;
    for ( u32 i = 0; i < ENTITY_MULTIPLIER; ++i )
    {
        for ( u32 j = 0; j < ENTITY_MULTIPLIER; ++j )
        {
            f32 x = ENTITY_SEPARATION * (f32)i - 0.5f * ENTITY_MULTIPLIER * ENTITY_SEPARATION;
            f32 z = ENTITY_SEPARATION * (f32)j - 0.5f * ENTITY_MULTIPLIER * ENTITY_SEPARATION;
            AddModelEntity( scene, scene.patrickModelIndex, TransformPositionScale( vec3( x, 1.5f, z ), vec3( 0.45f ) ) );
        }
    }

    // Lights
    AddDirectionalLight( scene, vec3( 0.8, 0.8, 0.8 ), normalize( vec3( 1.0, 1.0, 1.0 ) ) );
    AddPointLight(scene, vec3(2.0, 1.5, 0.5), vec3( 0.0, 0.5, -4.0));
    AddPointLight(scene, vec3(2.0, 1.5, 0.5), vec3( 4.0, 0.5,  3.0));
    AddPointLight(scene, vec3(2.0, 1.5, 0.5), vec3(-4.0, 0.5,  3.0));
}

void Init(App* app)
{
    gApp = app;

    Device& device = app->device;

    InitDevice(device);

    InitEmbedded(device, app->embedded);

    InitDebugDraw(device, app->debugDraw);

    InitForwardRender(device, app->forwardRenderData);

    InitScene(device, app->scene, app->embedded);

    app->globalParamsBlockSize = KB(1); // TODO: Get the size from the shader?
    app->localParamsBlockSize  = KB(1); // TODO: Get the size from the shader?

    app->colorRenderTargetIdx = CreateRenderTarget(device, MakeString("Color"), RenderTargetType_Color, app->displaySize);
    app->depthRenderTargetIdx = CreateRenderTarget(device, MakeString("Depth"), RenderTargetType_Depth, app->displaySize);
    Attachment attachments[] = {
        {GL_COLOR_ATTACHMENT0, app->colorRenderTargetIdx},
        {GL_DEPTH_ATTACHMENT,  app->depthRenderTargetIdx},
    };
    app->colorDepthPassIdx = CreateRenderPass(device, ARRAY_COUNT(attachments), attachments);

    app->frameRenderGroup = RegisterRenderGroup(app, "Frame");

    ProfileEvent_Init(app);

    app->mode = Mode_ForwardRender;
}

void DebugDraw_Render(Device& device, Embedded& embedded, DebugDraw& debugDraw, BufferRange& globalParams)
{
    if (debugDraw.opaqueLineCount > 0)
    {
        RENDER_GROUP("Debug draw - opaque lines");

        const Program& program = device.programs[debugDraw.opaqueProgramIdx];
        glUseProgram(program.handle);

        glBindBufferRange(GL_UNIFORM_BUFFER, BINDING(0), device.constantBuffers[globalParams.bufferIdx].handle, globalParams.offset, globalParams.size);

        glBindVertexArray(debugDraw.opaqueLineVao.handle);

        glDrawArrays(GL_LINES, 0, debugDraw.opaqueLineCount * 2);
    }

    if (debugDraw.texQuadCount > 0)
    {
        RENDER_GROUP("Debug draw - textured quads");

        Program& program = device.programs[embedded.texturedGeometryProgramIdx];
        glUseProgram(program.handle);

        Mesh& mesh = device.meshes[embedded.meshIdx];
        GLuint vaoHandle = FindVAO(mesh, embedded.blitSubmeshIdx, program);
        glBindVertexArray(vaoHandle);

        glDisable(GL_DEPTH_TEST);
        glDisable(GL_BLEND);

        for (u32 i = 0; i < debugDraw.texQuadCount; ++i)
        {
            ivec4 viewportRect = debugDraw.texQuadRects[i];
            glViewport(viewportRect.x, viewportRect.y, viewportRect.z, viewportRect.w);

            glActiveTexture(GL_TEXTURE0);
            GLuint textureHandle = debugDraw.texQuadTextureHandles[i];
            glBindTexture(GL_TEXTURE_2D, textureHandle);
            glUniform1i(embedded.texturedGeometryProgram_TextureLoc, 0);

            glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_INT, 0);
        }

        glBindVertexArray(0);
        glUseProgram(0);
    }
}

void ForwardShading_Update(const Device& device, const Scene& scene, ForwardRenderData& forwardRender)
{
//	return;
//	MapBuffer(forwardRender.instancingBuffer);
//
//	forwardRender.renderPrimitives.clear();
//
//    for (u32 i = 0; i < app->scene.entities.size(); ++i)
//    {
//        Entity&     entity = app->scene.entities[i];
//        const mat4& world  = entity.worldMatrix;
//        const mat4& worldViewProjection = projection * view * world;
//
//		RenderPrimitive renderPrimitive = {};
//		renderPrimitive.vaoHandle = FindVAO();
//		renderPrimitive.albedoTextureHandle = ;
//		renderPrimitive.indexCount = ;
//		renderPrimitive.indexOffset = ;
//		renderPrimitive.instanceCount = 1;
//		renderPrimitive.instancingOffset = forwardRender.instancingBuffer.head;
//
//		PushAlignedData(forwardRender.instancingBuffer, world, 1);
//		PushAlignedData(forwardRender.instancingBuffer, worldViewProjection, 1);
//
//		forwardRender.renderPrimitives.push_back(renderPrimitive);
//    }
//
//	UnmapBuffer(forwardRender.instancingBuffer);
}

void ForwardShading_Render(Device& device, const Embedded& embedded, const ForwardRenderData& forwardRender, const BufferRange& globalParamsRange, const std::vector<Entity>& entities)
{
    const Program& program = device.programs[forwardRender.programIdx];
    glUseProgram(program.handle);

    if (device.glVersion < MAKE_GLVERSION(4, 2))
    {
        const GLuint globalParamsIndex = glGetUniformBlockIndex(program.handle, "GlobalParams");
        const GLuint localParamsIndex = glGetUniformBlockIndex(program.handle, "LocalParams");
        glUniformBlockBinding(program.handle, globalParamsIndex, BINDING(0));
        glUniformBlockBinding(program.handle, localParamsIndex, BINDING(1));
    }

    glBindBufferRange(GL_UNIFORM_BUFFER, BINDING(0), device.constantBuffers[globalParamsRange.bufferIdx].handle, globalParamsRange.offset, globalParamsRange.size);

#if 1

	const std::vector<RenderPrimitive>& renderPrimitives = forwardRender.renderPrimitives;

    for (u32 i = 0; i < renderPrimitives.size(); ++i)
    {
        const RenderPrimitive& renderPrimitive = renderPrimitives[i];

        glBindVertexArray(renderPrimitive.vaoHandle);

        BindBuffer(forwardRender.instancingBuffer);
        const u32 VertexStream_FirstInstancingStream = 6;
        const GLsizei stride = sizeof(mat4) * 2;
        u64 offset = renderPrimitive.instancingOffset;
        for (u32 location = VertexStream_FirstInstancingStream; location < 14; ++location)
        {
            glVertexAttribPointer(location, 4, GL_FLOAT, GL_FALSE, stride, (void*)(u64)offset);
            glVertexAttribDivisor(location, 1);
            glEnableVertexAttribArray(location);
            offset += sizeof(vec4);
        }

        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_2D, renderPrimitive.albedoTextureHandle);
        glUniform1i(forwardRender.uniLoc_Albedo, 0);

        glDrawElementsInstanced(GL_TRIANGLES, renderPrimitive.indexCount, GL_UNSIGNED_INT, (void*)(u64)renderPrimitive.indexOffset, renderPrimitive.instanceCount);
    }
#endif

    for (u32 i = 0; i < entities.size(); ++i)
    {
        const Entity& entity = entities[i];

        // If we store all information in a struct like this before
        // the code below will simplify a lot.
        //struct ForwardRenderPrimitive
        //{
        //    GLuint vaoId;
        //    u32    indexCount;
        //    u32    indexOffset;
        //    GLuint bufferId;
        //    GLuint blockOffset;
        //    GLuint blockOffset;
        //    GLuint texId;
        //};

        if (entity.type == EntityType_Model)
        {
            GLuint bufferHandle = device.constantBuffers[entity.localParamsBufferIdx].handle;
            glBindBufferRange(GL_UNIFORM_BUFFER, BINDING(1), bufferHandle, entity.localParamsOffset, entity.localParamsSize);

            Model& model = device.models[entity.modelIndex];
            Mesh& mesh = device.meshes[model.meshIdx];

            for (u32 i = 0; i < mesh.submeshes.size(); ++i)
            {
                GLuint vao = FindVAO(mesh, i, program);
                glBindVertexArray(vao);

                Submesh& submesh = mesh.submeshes[i];
                u32 submeshMaterialIdx = model.materialIdx[i];
                Material& submeshMaterial = device.materials[submeshMaterialIdx];
                glActiveTexture(GL_TEXTURE0);
                glBindTexture(GL_TEXTURE_2D, device.textures[submeshMaterial.albedoTextureIdx].handle);
                glUniform1i(forwardRender.uniLoc_Albedo, 0);

                glDrawElements(GL_TRIANGLES, submesh.indexCount, GL_UNSIGNED_INT, (void*)(u64)submesh.indexOffset);
            }
        }
        else if (entity.type == EntityType_Mesh)
        {
            GLuint bufferHandle = device.constantBuffers[entity.localParamsBufferIdx].handle;
            glBindBufferRange(GL_UNIFORM_BUFFER, BINDING(1), bufferHandle, entity.localParamsOffset, entity.localParamsSize);

            Mesh& mesh = device.meshes[entity.meshIndex];

            GLuint vao = FindVAO(mesh, entity.submeshIndex, program);
            glBindVertexArray(vao);

            Material& defaultMaterial = device.materials[embedded.defaultMaterialIdx];
            glActiveTexture(GL_TEXTURE0);
            glBindTexture(GL_TEXTURE_2D, device.textures[defaultMaterial.albedoTextureIdx].handle);
            glUniform1i(forwardRender.uniLoc_Albedo, 0);

            Submesh& submesh = mesh.submeshes[entity.submeshIndex];
            glDrawElements(GL_TRIANGLES, submesh.indexCount, GL_UNSIGNED_INT, (void*)(u64)submesh.indexOffset);
        }
    }
}

void BeginFrame(App* app)
{
    app->frame++;
    app->frameMod = app->frame % MAX_GPU_FRAME_DELAY;

    ProfileEvent_BeginFrame(app);

    DebugDraw_MapBuffers(app->debugDraw);
}

void Gui(App* app)
{
    DebugDraw_Clear(app->debugDraw);

    Device& device = app->device;

    ImGui::Begin("Info");
    ImGui::Text("Device name: %s", device.name);
    ImGui::Text("OGL Version: %s", device.glVersionString);
    ImGui::Text("FPS: %f", 1.0f/app->deltaTime);

    ImGui::Separator();
    
    ImGui::Text("Camera");
    float yawPitch[3] = {360.0f * app->scene.mainCamera.yaw / TAU, 360.0f * app->scene.mainCamera.pitch / TAU};
    ImGui::InputFloat3("Yaw/Pitch/Roll", yawPitch, "%.3f", ImGuiInputTextFlags_ReadOnly);
    ImGui::InputFloat3("Position", value_ptr(app->scene.mainCamera.position), "%.3f", ImGuiInputTextFlags_ReadOnly);
    
    ImGui::Separator();

    if (ImGui::Button("Take snapshot"))
    {
        app->takeSnapshot = true;
    }

    ImGui::Separator();

    for (u32 renderGroupIdx = 0; renderGroupIdx < app->renderGroupCount; ++renderGroupIdx)
    {
        f32 timeMs = 0.0f;
        if (app->frame >= MAX_GPU_FRAME_DELAY )
        {
            const GLuint beginTimerQuery = app->timerQueries[ GetTimerQueryIndex(app->frameMod, renderGroupIdx, 0) ];
            const GLuint endTimerQuery   = app->timerQueries[ GetTimerQueryIndex(app->frameMod, renderGroupIdx, 1) ];
            GLint endTimerQueryAvailable = 0;
            while (!endTimerQueryAvailable)
                glGetQueryObjectiv(endTimerQuery, GL_QUERY_RESULT_AVAILABLE, &endTimerQueryAvailable);
            GLuint64 beginTimeNs;
            GLuint64 endTimeNs;
            glGetQueryObjectui64v(beginTimerQuery, GL_QUERY_RESULT, &beginTimeNs);
            glGetQueryObjectui64v(endTimerQuery,   GL_QUERY_RESULT, &endTimeNs);
            timeMs = (endTimeNs - beginTimeNs) / 1000000.0f;
        }
        char buf[128];
        sprintf(buf, "%.03f (ms)", timeMs);
        ImGui::PushStyleVar(ImGuiStyleVar_ButtonTextAlign, ImVec2(1.0, 0.5));
        ImGui::ProgressBar(timeMs/16.0f, ImVec2(0.0f, 0.0f), buf);
        ImGui::PopStyleVar();
        ImGui::SameLine();
        ImGui::Text("%s", app->renderGroups[renderGroupIdx].name);
    }

    ImGui::Separator();

    const char* renderScripts[] = {"Forward naive"};
    static const char* currentItem = renderScripts[0];
    if (ImGui::BeginCombo("Render script", currentItem))
    {
        for (u32 itemIdx = 0; itemIdx < ARRAY_COUNT(renderScripts); ++itemIdx)
        {
            bool isSelected = currentItem == renderScripts[itemIdx];
            if (ImGui::Selectable(renderScripts[itemIdx], isSelected))
                currentItem = renderScripts[itemIdx];
            if (isSelected)
                ImGui::SetItemDefaultFocus();
        }
        ImGui::EndCombo();
    }

    ImGui::Separator();

    static u32    visibleTextureCount = 0;
    static GLuint visibleTextures[16];

    u32    newVisibleTexturesCount = 0;
    GLuint newVisibleTextures[16];

    u32 yOffset = 0;

    if (ImGui::CollapsingHeader("Textures"))
    {
        for (u32 i = 1; i < app->device.textures.size(); ++i)
        {
            const Texture& texture = app->device.textures[i];

            bool showInDebugDraw = false;
            for (u32 i = 0; i < visibleTextureCount && !showInDebugDraw; ++i)
                showInDebugDraw = (visibleTextures[i] == texture.handle);

            ImGui::Checkbox(texture.filepath.c_str(), &showInDebugDraw);

            if (showInDebugDraw)
            {
                ASSERT(newVisibleTexturesCount < ARRAY_COUNT(newVisibleTextures), "Debug textured quads limit reached");
                newVisibleTextures[newVisibleTexturesCount++] = texture.handle;

                const ivec4 rect(0, yOffset, 64, 64);
                DebugDrawTexturedQuad(app->debugDraw, texture.handle, rect);
                yOffset += 64;
            }
        }
    }

    if (ImGui::CollapsingHeader("Render targets"))
    {
        for (u32 i = 1; i < app->device.renderTargets.size(); ++i)
        {
            const RenderTarget& renderTarget = app->device.renderTargets[i];

            bool showInDebugDraw = false;
            for (u32 i = 0; i < visibleTextureCount && !showInDebugDraw; ++i)
                showInDebugDraw = (visibleTextures[i] == renderTarget.handle);

            ImGui::Checkbox(renderTarget.name.str, &showInDebugDraw);

            if (showInDebugDraw)
            {
                ASSERT(newVisibleTexturesCount < ARRAY_COUNT(newVisibleTextures), "Debug textured quads limit reached");
                newVisibleTextures[newVisibleTexturesCount++] = renderTarget.handle;

                const ivec4 rect(0, yOffset, 64, 64);
                DebugDrawTexturedQuad(app->debugDraw, renderTarget.handle, rect);
                yOffset += 64;
            }
        }
    }

    visibleTextureCount = newVisibleTexturesCount;
    for (u32 i = 0; i < visibleTextureCount; ++i)
        visibleTextures[i] = newVisibleTextures[i];

    ImGui::End();

    //ImGui::ShowDemoWindow();
}

void Resize(App* app)
{
    Device& device = app->device;

    // Resize render targets
    for (u32 i = 0; i < device.renderTargets.size(); ++i)
    {
        RenderTarget& renderTarget = device.renderTargets[i];
        DestroyRenderTargetRaw(renderTarget);
        renderTarget = CreateRenderTargetRaw(renderTarget.name, app->displaySize, renderTarget.type);
    }

    // Recreate render passes
    for (u32 i = 0; i < device.renderPasses.size(); ++i)
    {
        RenderPass& renderPass = device.renderPasses[i];
        DestroyRenderPassRaw(renderPass);
        renderPass = CreateRenderPassRaw(device, renderPass.attachmentCount, renderPass.attachments);
    }
}

void Update(App* app)
{
    if (app->input.keys[K_M] == BUTTON_PRESS)
        app->mode = (Mode)((app->mode + 1) % Mode_Count);

    if (app->input.keys[K_T] == BUTTON_PRESS)
        app->textureIndexShown++;

    if (app->input.mouseButtons[LEFT] == BUTTON_PRESS)
        ILOG("Mouse button left pressed");

    if (app->input.mouseButtons[LEFT] == BUTTON_RELEASE)
        ILOG("Mouse button left released");

    for (u64 i = 0; i < app->device.programs.size(); ++i)
    {
        Program& program = app->device.programs[i];
        u64 currentTimestamp = GetFileLastWriteTimestamp(program.filepath.c_str());
        if (currentTimestamp > program.lastWriteTimestamp)
        {
            glDeleteProgram(program.handle);
            String programSource = ReadTextFile(program.filepath.c_str());
            const char* programName = program.programName.c_str();
            program.handle = CreateProgramFromSource(programSource, app->device.glslVersion, programName);
            program.vertexInputLayout = ExtractVertexShaderLayoutFromProgram(program.handle);
            program.lastWriteTimestamp = currentTimestamp;
        }
    }

    // Update camera
    Camera& camera = app->scene.mainCamera;

    const float rotationSpeed = 0.1f * PI;
    if (app->input.mouseButtons[RIGHT] == BUTTON_PRESSED)
    {
        camera.yaw += app->input.mouseDelta.x * rotationSpeed * app->deltaTime;
        camera.pitch -= app->input.mouseDelta.y * rotationSpeed * app->deltaTime;
    }
    camera.yaw = mod(camera.yaw, TAU);
    camera.pitch = clamp(camera.pitch, -PI/2.1f, PI/2.1f);
    camera.forward = vec3(cosf(camera.pitch)*sinf(camera.yaw),
                               sinf(camera.pitch),
                               -cosf(camera.pitch)*cosf(camera.yaw));
    camera.right = vec3(cosf(camera.yaw), 0.0f, sinf(camera.yaw));
    vec3 upVector = vec3(0.0f, 1.0f, 0.0f);

    vec3 newDirection = vec3(0.0);
    if (app->input.keys[K_W] == BUTTON_PRESSED) { newDirection += camera.forward; }
    if (app->input.keys[K_S] == BUTTON_PRESSED) { newDirection -= camera.forward; }
    if (app->input.keys[K_D] == BUTTON_PRESSED) { newDirection += camera.right;   }
    if (app->input.keys[K_A] == BUTTON_PRESSED) { newDirection -= camera.right;   }

    const float newdirMagnitude = length(newDirection);
    newDirection = (newdirMagnitude > 0.0f) ? newDirection / newdirMagnitude : vec3(0.0f);

    float speedMagnitude = length(camera.speed);
    vec3 speedDirection = (speedMagnitude > 0.0f) ? camera.speed / speedMagnitude : vec3(0.0f);

    const float MAX_SPEED = 100.0f;
    if (newdirMagnitude > 0.0f) {
        speedDirection = 0.5f * (speedDirection + newDirection);
        speedMagnitude = min(speedMagnitude + 1.0f, MAX_SPEED);
    } else {
        speedMagnitude *= 0.8f;
        if (speedMagnitude < 0.01f)
            speedMagnitude = 0.0f;
    }

    camera.speed = speedMagnitude * speedDirection;

    camera.position += camera.speed * app->deltaTime;

    float aspectRatio = (float)app->displaySize.x/(float)app->displaySize.y;
    mat4 projection = perspective(radians(60.0f), aspectRatio, 0.1f, 1000.0f);
    mat4 view       = lookAt(camera.position, camera.position + camera.forward, upVector);

    // Upload uniforms to buffer

    BeginConstantBufferRecording( app );

    Buffer& constantBuffer = GetMappedConstantBufferForRange( app, app->globalParamsBlockSize );

    // -- Global params
    app->globalParamsBufferIdx = app->currentConstantBufferIdx;
    app->globalParamsOffset = constantBuffer.head;

    mat4 viewProjection = projection * view;
    PushMat4(constantBuffer, viewProjection);
    PushVec3(constantBuffer, camera.position);

    PushUInt(constantBuffer, app->scene.lights.size());

    for (u32 i = 0; i < app->scene.lights.size(); ++i)
    {
        AlignHead(constantBuffer, sizeof(vec4));

        Light& light = app->scene.lights[i];
        PushUInt(constantBuffer, light.type);
        PushVec3(constantBuffer, light.color);
        PushVec3(constantBuffer, light.direction);
        PushVec3(constantBuffer, light.position);
    }

    app->globalParamsSize = constantBuffer.head - app->globalParamsOffset;

    // -- Local params
    for (u32 i = 0; i < app->scene.entities.size(); ++i)
    {
        Buffer& constantBuffer = GetMappedConstantBufferForRange( app, app->localParamsBlockSize );

        Entity&     entity = app->scene.entities[i];
        const mat4& world  = entity.worldMatrix;
        const mat4& worldViewProjection = projection * view * world;

        entity.localParamsBufferIdx = app->currentConstantBufferIdx;
        entity.localParamsOffset = constantBuffer.head;
        PushMat4(constantBuffer, world);
        PushMat4(constantBuffer, worldViewProjection);
        entity.localParamsSize = constantBuffer.head - entity.localParamsOffset;
    }

    EndConstantBufferRecording( app );

	ForwardShading_Update(app->device, app->scene, app->forwardRenderData);

#if 0
    // Some debug drawing
    for (u32 i = 0; i < app->scene.entities.size(); ++i)
    {
        Entity& entity = app->scene.entities[i];
        DebugDrawLine(app->debugDraw, entity.worldMatrix[3], vec3(entity.worldMatrix[3]) + vec3(0.0, 5.0, 0.0), vec3(1.0, 0.0, 0.0));
    }
#endif

    DebugDraw_UnmapBuffers(app->debugDraw);
}

void BlitTexture(Device& device, Embedded& embedded, ivec4 viewportRect, GLuint textureHandle)
{
    glViewport(viewportRect.x, viewportRect.y, viewportRect.z, viewportRect.w);

    Program& program = device.programs[embedded.texturedGeometryProgramIdx];
    glUseProgram(program.handle);

    Mesh& mesh = device.meshes[embedded.meshIdx];
    GLuint vaoHandle = FindVAO(mesh, embedded.blitSubmeshIdx, program);
    glBindVertexArray(vaoHandle);

    glDisable(GL_DEPTH_TEST);
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

    glUniform1i(embedded.texturedGeometryProgram_TextureLoc, 0);
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, textureHandle);

    glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_INT, 0);

    glBindVertexArray(0);
    glUseProgram(0);
}

void Render(App* app)
{
    Device& device = app->device;

    switch (app->mode)
    {
        case Mode_BlitTexture:
            {
                GLuint textureHandle = device.textures[app->textureIndexShown % device.textures.size()].handle;
                ivec4 viewportRect(0, 0, app->displaySize.x, app->displaySize.y);
                BlitTexture(app->device, app->embedded, viewportRect, textureHandle);
            }
            break;

        case Mode_ForwardRender:
            {
                RENDER_GROUP("Forward render");

                BeginRenderPass(device, app->colorDepthPassIdx);

                glViewport(0.0f, 0.0f, app->displaySize.x, app->displaySize.y);
                glEnable(GL_DEPTH_TEST);

                BufferRange globalParamsRange = {
                    app->globalParamsBufferIdx,
                    app->globalParamsOffset,
                    app->globalParamsSize
                };

                ForwardShading_Render(app->device, app->embedded, app->forwardRenderData, globalParamsRange, app->scene.entities);

                DebugDraw_Render(device, app->embedded, app->debugDraw, globalParamsRange);

                glBindVertexArray(0);

                glUseProgram(0);

                EndRenderPass(device);
            }
            {
                RenderTarget& renderTarget = device.renderTargets[app->colorRenderTargetIdx];
                ivec4 viewportRect(0, 0, app->displaySize.x, app->displaySize.y);
                BlitTexture(app->device, app->embedded, viewportRect, renderTarget.handle);
            }
            break;

        default:;
    }

    //
    // Read pixels
    //

    if (app->takeSnapshot)
    {
        glFinish();

        const u32 width = app->displaySize.x;
        const u32 height = app->displaySize.y;
        u8* outPixels = new u8[width*height*3];
        glReadPixels(0, 0, width, height, GL_RGB, GL_UNSIGNED_BYTE, outPixels);
        stbi_write_png("snapshot.png", width, height, 3, (const void*)outPixels, width*3);
        delete[] outPixels;
    }
}

void EndFrame(App* app)
{
    ProfileEvent_EndFrame(app);
}

